---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  ## Install ansible
  #- pip install ansible
 
  ## Check ansible version
  #- ansible --version

  ## Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic script syntax check
  - bash -n update.sh
  - bash -n gitkeep.sh
  - bash -n gitfilesupdate.sh
  # Run
  - bash gitkeep.sh |grep " Gitkeep directory '.'."
  - bash gitkeep.sh /tmp |grep " Gitkeep directory '/tmp'."

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
#  email:
#  - youremailaddress

