---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: minimal

# Use the new container infrastructure
sudo: false

# Install packages
install: true

# Run
script:

  # Git files update
  - |
    set -x
    gitconf_dir="${HOME}/.config/git"
    : "" && {
      bash -n update.sh &&
      bash -n gitfilesupdate.sh &&
      : "OK"
    } || exit 1
    : "Run with -g" && {
      rm -rf "${gitconf_dir}" || :
      mkdir -p "${gitconf_dir}" &&
      bash -- gitfilesupdate.sh -g &&
      [   -r "${gitconf_dir}/ignore" ] &&
      [   -r "${gitconf_dir}/attributes" ] &&
      [   -x "${gitconf_dir}/gitfilesupdate.sh" ] &&
      [   -x "${gitconf_dir}/gitkeep.sh" ] &&
      [ ! -r "${gitconf_dir}/config" ] &&
      [ ! -r "${gitconf_dir}/config.local.tmplt" ] &&
      : "OK"
    } || exit 2
    : "Run with -g and -c" && {
      rm -rf "${gitconf_dir}" || :
      mkdir -p "${gitconf_dir}" &&
      bash -- gitfilesupdate.sh -g -c &&
      [ -r "${gitconf_dir}/ignore" ] &&
      [ -r "${gitconf_dir}/attributes" ] &&
      [ -x "${gitconf_dir}/gitfilesupdate.sh" ] &&
      [ -x "${gitconf_dir}/gitkeep.sh" ] &&
      [ -r "${gitconf_dir}/config" ] &&
      [ -r "${gitconf_dir}/config.local.tmplt" ] &&
      : "OK"
    } || exit 3

  # Gitkeep
  - |
    set -x
    base_dir=$(pwd)
    bash -n gitkeep.sh &&
    mkdir -p t/{dir1,dir2,dir3/child1,dir3/child2} &&
    : "" && {
      find ./t -type f -exec rm -f {} \; || :
      touch t/dir1/file1.txt &&
      touch t/dir3/child1/file2.txt &&
      bash -- "${base_dir}/gitkeep.sh" ./t &&
      [ ! -r "t/dir1/.gitkeep" ] &&
      [   -r "t/dir2/.gitkeep" ] &&
      [ ! -r "t/dir3/child1/.gitkeep" ] &&
      [   -r "t/dir3/child2/.gitkeep" ] &&
      mv -f t/dir{1,2}/file1.txt &&
      mv -f t/dir3/child{1,2}/file2.txt &&
      bash -- "${base_dir}/gitkeep.sh" --rebuild ./t &&
      [   -r "t/dir1/.gitkeep" ] &&
      [ ! -r "t/dir2/.gitkeep" ] &&
      [   -r "t/dir3/child1/.gitkeep" ] &&
      [ ! -r "t/dir3/child2/.gitkeep" ] &&
      : "OK"
    };

# Notifications
#notifications:
#  email:
#  - your@emailaddress

